// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model


type Mutation struct {
}

type Order struct {
	ID       string `json:"id", bson:"_id"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	Status   string `json:"status"`
}

type OrderInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	Status   string `json:"status"`
}

type Product struct {
	ID          string  `json:"id", bson:"_id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id", bson:"_id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
